name: .NET

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types: [opened]
    branches:
      - lab-2
    paths:
      - 'feature/**'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore AdsService/AdsService.sln 
    - name: Build
      run: dotnet build AdsService/AdsService.sln --no-restore